// <auto-generated />
using System;
using DigitalisationDesTableauxDeBordAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckFillingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608102908_RemoveDummyTemp2")]
    partial class RemoveDummyTemp2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.AdminSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisabledTabKeysJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AdminSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisabledTabKeysJson = "[]",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Domaine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Domaines", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Kpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SousDomaineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SousDomaineId", "Nom")
                        .IsUnique();

                    b.ToTable("Kpis", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nom");

                    b.Property<string>("VillesJson")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("wilayas");

                    b.HasKey("Id");

                    b.ToTable("DR", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.SousDomaine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DomaineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomaineId");

                    b.ToTable("SousDomaines", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.SousKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KpiId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KpiId", "Order")
                        .IsUnique();

                    b.ToTable("SousKpis", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.StepComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Annee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mois")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TabKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StepComments");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Tableau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Annee")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mois")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TabKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("IsApproved");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TabKey", "Mois", "Annee");

                    b.ToTable("Tableau", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedDomaines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedKpis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedSousDomaines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedDomaines = "",
                            AllowedKpis = "",
                            AllowedSousDomaines = "",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "Test",
                            Email = "test@gmail.com",
                            FirstName = "Test",
                            LastName = "User",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$3f1y0aSd2iVFhKoWi60oVuwBiNQb913o5x94e0pYXB9eaqvHXW1By",
                            PhoneNumber = "0661000000",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AllowedDomaines = "",
                            AllowedKpis = "",
                            AllowedSousDomaines = "",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "Administration",
                            Email = "admin@test.com",
                            FirstName = "Admin",
                            LastName = "Test",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$3f1y0aSd2iVFhKoWi60oVuwBiNQb913o5x94e0pYXB9eaqvHXW1By",
                            PhoneNumber = "0661999999",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 3,
                            AllowedDomaines = "",
                            AllowedKpis = "",
                            AllowedSousDomaines = "",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "Administration",
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Gmail",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$3f1y0aSd2iVFhKoWi60oVuwBiNQb913o5x94e0pYXB9eaqvHXW1By",
                            PhoneNumber = "0661999998",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Valeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Debit_Ecart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Debit_Objectif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Debit_Realise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ecart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Evol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_Periode")
                        .HasColumnType("int");

                    b.Property<int>("Id_SousKpi")
                        .HasColumnType("int");

                    b.Property<decimal?>("M")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MTTR_Ecart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MTTR_Objectif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MTTR_Realise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_CDD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_CDI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_CTA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Cadres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Cadres_Sup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Execution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Maitrise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Montant_Recouvre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Objectif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Realise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Recrute")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_1_Taux")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_CDD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_CDI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_CTA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Cadres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Cadres_Sup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Execution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Maitrise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Montant_Mis_Recouvrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Montant_Recouvre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Objectif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Objectif_Recouvrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Realise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Recrute")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Taux")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("M_Taux_Recouvrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("M_Wilaya")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Objectif_2026")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Part_Pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Situation_Actuelle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Taux_M")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Taux_M_1")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_SousKpi", "Id_Periode")
                        .IsUnique();

                    b.ToTable("Valeurs", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Wilaya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("Wilaya", (string)null);
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.AuditLog", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Kpi", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.SousDomaine", "SousDomaine")
                        .WithMany("Kpis")
                        .HasForeignKey("SousDomaineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SousDomaine");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.SousDomaine", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.Domaine", "Domaine")
                        .WithMany("SousDomaines")
                        .HasForeignKey("DomaineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domaine");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.SousKpi", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.Kpi", "Kpi")
                        .WithMany("SousKpis")
                        .HasForeignKey("KpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpi");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.StepComment", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Tableau", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Valeur", b =>
                {
                    b.HasOne("DigitalisationDesTableauxDeBordAPI.Models.SousKpi", "SousKpi")
                        .WithMany()
                        .HasForeignKey("Id_SousKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SousKpi");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Domaine", b =>
                {
                    b.Navigation("SousDomaines");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.Kpi", b =>
                {
                    b.Navigation("SousKpis");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.SousDomaine", b =>
                {
                    b.Navigation("Kpis");
                });

            modelBuilder.Entity("DigitalisationDesTableauxDeBordAPI.Models.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
